spring:
  data:
    mongodb:
      uri: mongodb://mongo:mongo1234@localhost:27017/mongo
      database: mongo
  application:
    name: m-link

server:
  port: 8082

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka